'use client'
import {useRouter} from "next/navigation";
import Header from '~/components/Header';
import Footer from '~/components/Footer';
import HeadInfo from "~/components/HeadInfo";

const PageComponent = ({locale = ''}) => {
  const router = useRouter();

  return (
    <>
      <HeadInfo
        title='Sora Magic - Blog'
        description=''
        locale={locale}
        page={"/blog"}
      />
      <Header locale={locale} page={"blog"} indexLanguageText=''/>
      <div className="container">
        <div id="faqs" className="justify-centermx-auto flex w-full max-w-7xl flex-col items-center px-5 md:px-10 md:py-24 lg:py-32">
          <div className="mx-auto flex max-w-[550px] flex-col items-center justify-center px-0 text-center lg:max-w-[800px] lg:px-10">
            <h1 className="mx-auto text-center font-bold text-white text-3xl lg:text-5xl">What is sora?</h1>
          </div>
          <div className="mt-10 flex w-full flex-col">            
            <div className="relative w-full rounded-md px-12">
              <div>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">On February 16, 2024, Open AI announced the launch of a new generative artificial intelligence model "Sora". It is understood that through text commands, Sora can directly output videos up to 60 seconds long, and contain highly detailed backgrounds, complex multi-angle shots, and multiple emotional characters.</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">This means that, following text and images, OpenAI has expanded its advanced AI technology to the video field. OpenAI also stated that Sora is the basis for models that can understand and simulate the real world. This ability will be an important milestone in the realization of AGI (artificial general intelligence).</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">The industry has actually long expected the emergence of the OpenAI video generation model, but some people still commented that "it is coming faster than expected", and some people said excitedly that "we really see the new industrial revolution coming."</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">Let's take a look at the video generated by Sora.</p>                
              </div>
            </div>            
            <div className="relative w-full rounded-md px-12">              
              <div className="flex justify-center items-start">
                <video
                  src="https://cdn.openai.com/sora/videos/tokyo-walk.mp4"
                  controls={true}
                  autoPlay={false}
                  playsInline={true}
                  preload={"metadata"}
                  controlsList={"nodownload"}
                  style={{width: '100%', height: '420px'}}
                />
              </div>
            </div>
            <div className="relative my-3 w-full rounded-md px-12 py-0">
              <div>
                <h2 className="font-bold text-white text-3xl">What is advantages of Sora?</h2>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">Although sora is not the first AI model to launch Vincent Video, it has more advantages than other models.</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">Let’s take a look at the comparison between Sora and other models.</p>
                <div className="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                  <table className="min-w-full divide-y divide-gray-700">
                    <thead>
                      <tr>
                        <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-white sm:pl-0"></th>
                        <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-white">Sora</th>
                        <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-white">Others</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-800">
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">video duration</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">60 seconds</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">2~4 seconds</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">world understanding</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">yes</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">week</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">digital world simulation</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">support</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">not support</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">object consistency</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">powerful</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">week</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">object persistence/continuity</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">powerful</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">week</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">architecture</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">Transformer</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">Mainly U-Net</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">text understanding</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">powerful</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">generally</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">clarity</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">1080P</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">up to 4K</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">sport control</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">prompt words</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">prompt words + motion control tools</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">Extension to generate video</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">before/after</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">back</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">Drive mode</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">data</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">picture</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">video to video editing</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">support</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">part</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">world interaction ability</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">support</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">not support</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">native aspect ratio</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">support</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">not support</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">Seamless connectivity</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">powerful</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">weak</td>
                      </tr>
                      <tr>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">3D motion continuity</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">powerful</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-300">weak</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">After sorting out the official technical report, the reporter of "Daily Economic News" summarized Sora's 6 major advantages:​</p>
                <br/>
                <h3 className="font-bold text-white text-xl">(1) Accuracy and Diversity</h3>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">One of Sora's distinguishing features is its ability to accurately interpret long prompts of up to 135 words. It accurately interprets user-supplied text input and generates high-quality video clips with a variety of scenes and characters.</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">This new tool converts short text descriptions into one-minute high-definition videos. It covers a wide range of topics, from people and animals to lush landscapes, city scenes, gardens, and even underwater New York City, offering diverse content based on user requirements.​</p>
                <br/>
                <h3 className="font-bold text-white text-xl">(2) Powerful language understanding</h3>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">OpenAI uses the re-captioning technology of the Dall-E model to generate descriptive subtitles of visual training data, which not only improves the accuracy of the text, but also improves the overall quality of the video. </p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">In addition, similar to DALL·E 3, OpenAI also utilizes GPT technology to convert short user prompts into longer detailed translations and sends them to the video model. This enables Sora to produce high-quality videos exactly as the user prompts.​</p>
                <br/>
                <h3 className="font-bold text-white text-xl">(3) Generate videos from images/videos</h3>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">In addition to converting text into videos, Sora can also accept other types of input prompts, such as existing images or videos. </p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">This enables Sora to perform a wide range of image and video editing tasks, such as creating perfect looping videos, converting static images into animations, extending videos forward or backward, and more. </p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">OpenAI showed demo videos generated based on images of DALL·E 2 and DALL·E 3 in the report. This not only proves the power of Sora, but also demonstrates its unlimited potential in the field of image and video editing.</p>
                <br/>
                <h3 className="font-bold text-white text-xl">(4) Video extension function</h3>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">Since diverse input prompts are accepted, users can create videos based on images or supplement existing videos.</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">As a Transformer-based diffusion model, Sora can also expand video forward or backward along the timeline. Judging from the four demo videos provided by OpenAI, they all start from the same video clip and extend to the past of the timeline. </p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">So, despite the different beginnings, the videos all end the same.</p>
                <br/>
                <h3 className="font-bold text-white text-xl">(5) Excellent device adaptability</h3>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">Sora has excellent sampling capabilities, from widescreen 1920x1080p to vertical screen 1080x1920, and can easily handle any video size in between. </p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">This means Sora is able to generate content for a variety of devices that perfectly matches its original aspect ratio. And Sora can quickly prototype content at a small size before generating high-resolution content.​</p>
                <br/>
                <h3 className="font-bold text-white text-xl">(6) Consistency and continuity of scenes and objects</h3>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">Sora can generate videos with dynamic perspective changes, and the movement of characters and scene elements in three-dimensional space will appear more natural. Sora handles occlusion issues very well. </p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">One problem with existing models is that they may not be able to track objects when they leave the field of view. By providing predictions for multiple frames at once, Sora ensures that the subject of the frame remains intact even if it temporarily leaves the field of view.</p>
              </div>
            </div>
            <div className="relative my-3 w-full rounded-md px-12 py-0">
              <div>
                <h2 className="font-bold text-white text-3xl">Possible impact of Sora​</h2>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">If Sora can truly implement Vincent Video, what impact might it have?​</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">1. The emergence of film and television works without actors is a small challenge for actors. Real "virtual idols" will appear. Previous two-dimensional characters have not really reached the level of "idol".</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">2. It is beneficial to the screenwriting industry, and script and text creation capabilities have become core competitiveness.​</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">3. Sora may be the real Vincent video. Most of the previous Vincent videos were only 2 seconds long, and were only small movements of objects.​</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">4. OpenAI continues to widen its lead, putting pressure on many manufacturers who are still conducting large-scale model testing and scoring pk.​</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">5. The direct impact is on the film and television industry, especially the special effects industry. Using AI to produce some special effects and high-risk shots can significantly reduce shooting costs and avoid many dangers.</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">6. The photographer industry will also be affected. Using text to generate some videos can save a lot of shooting work.</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">7. After short videos became popular, video editors also became a popular profession. If the work of video editing can be replaced by AI, many video editors may be unemployed.​</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">8. For many short video creators, using AI to replace tedious editing work can greatly improve work efficiency.</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">9. Many singers shoot MVs with high costs. If AI can be used to generate the required MV images, a large part of the production costs can be saved.</p>
                <p className="font-inter mt-4 text-base font-light text-gray-500 whitespace-pre-line">10. In addition, if the real Vincent Video is realized, criminals may use this technology to commit new crimes.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer
        locale={locale}
        description=''
      />
    </>
  )
}
export default PageComponent
